"use client";

import { useEffect, useState, use as usePromise } from "react";
import Link from "next/link";
import { ArrowLeft, Copy, Check } from "lucide-react";
import { AppShell, PageHeader } from "@/components/app-shell";
import { JsonViewer } from "@/components/json-viewer";
import { SourceBadge } from "@/components/badges";

export default function FhirViewerPage({
  params,
}: {
  params: Promise<{ id: string; conditionId: string }>;
}) {
  const { id, conditionId } = usePromise(params);
  const [data, setData] = useState<{ resource: unknown; concept: { englishName: string } } | null>(null);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    fetch(`/api/fhir/condition/${id}/${conditionId}`)
      .then((r) => r.json())
      .then(setData);
  }, [id, conditionId]);

  async function copyJson() {
    if (!data) return;
    await navigator.clipboard.writeText(JSON.stringify(data.resource, null, 2));
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  }

  return (
    <AppShell>
      <PageHeader
        title="FHIR Resource Viewer"
        eyebrow={data ? `Condition · ${data.concept.englishName}` : "Condition"}
        description="Generated FHIR R4 Condition resource with double coding across NAMASTE, WHO TM2, and WHO ICD-11 Biomedicine."
        actions={
          <button
            onClick={copyJson}
            className="inline-flex items-center gap-1.5 rounded-md border border-[var(--color-line)] px-3 py-2 text-xs font-medium hover:border-[var(--color-teal-500)] transition-standard"
          >
            {copied ? <Check size={13} /> : <Copy size={13} />}
            {copied ? "Copied" : "Copy JSON"}
          </button>
        }
      />

      <div className="p-8 max-w-4xl space-y-4">
        <Link href={`/patients/${id}`} className="inline-flex items-center gap-1 text-sm text-[var(--color-ink-muted)] hover:text-[var(--color-teal-700)]">
          <ArrowLeft size={14} /> Back to patient profile
        </Link>

        <div className="flex gap-2">
          <SourceBadge source="namaste" />
          <SourceBadge source="tm2" />
          <SourceBadge source="biomedicine" />
        </div>

        {data ? (
          <JsonViewer data={data.resource} />
        ) : (
          <p className="text-sm text-[var(--color-ink-muted)]">Loading FHIR resource…</p>
        )}

        <p className="text-xs text-[var(--color-ink-muted)] max-w-2xl">
          This is a realistic FHIR R4 representation generated by the prototype for demonstration purposes.
          It is not certified for production clinical use.
        </p>
      </div>
    </AppShell>
  );
}
